# Generated by Django 3.1.2 on 2023-06-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230606_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CarritoCliente',
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
    ]
